// generated by deep-copy --pointer-receiver --type Participant --skip Links -o deepcopy_part.go .; DO NOT EDIT.

package models

// DeepCopy generates a deep copy of *Participant
func (o *Participant) DeepCopy() *Participant {
	var cp Participant = *o
	if o.Sessions != nil {
		cp.Sessions = make([]*Session, len(o.Sessions))
		copy(cp.Sessions, o.Sessions)
		for i2 := range o.Sessions {
			if o.Sessions[i2] != nil {
				cp.Sessions[i2] = new(Session)
				*cp.Sessions[i2] = *o.Sessions[i2]
			}
		}
	}
	return &cp
}
