package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"

	"github.com/empiricaly/tajriba/internal/graph/mgen"
	"github.com/empiricaly/tajriba/internal/runtime"
	errs "github.com/pkg/errors"
)

// RegisterService is the resolver for the registerService field.
func (r *mutationResolver) RegisterService(ctx context.Context, input mgen.RegisterServiceInput) (*mgen.RegisterServicePayload, error) {
	rt := runtime.ForContext(ctx)

	if r.srt != input.Token {
		return nil, runtime.ErrNotAuthorized
	}

	s, t, err := rt.RegisterService(ctx, input.Name, true)
	if err != nil {
		return nil, errs.Wrap(err, "register service")
	}

	return &mgen.RegisterServicePayload{Service: s, SessionToken: t}, nil
}
