package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"

	"github.com/empiricaly/tajriba/internal/graph/mgen"
	"github.com/empiricaly/tajriba/internal/runtime"
	errs "github.com/pkg/errors"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input mgen.LoginInput) (*mgen.LoginPayload, error) {
	rt := runtime.ForContext(ctx)

	u, s, err := rt.Login(ctx, input.Username, input.Password)
	if err != nil {
		return nil, errs.Wrap(err, "log in user")
	}

	return &mgen.LoginPayload{User: u, SessionToken: s}, nil
}

// TokenLogin is the resolver for the tokenLogin field.
func (r *mutationResolver) TokenLogin(ctx context.Context, input mgen.TokenLoginInput) (*mgen.LoginPayload, error) {
	rt := runtime.ForContext(ctx)

	u, s, err := rt.TokenLogin(ctx, input.Token)
	if err != nil {
		return nil, errs.Wrap(err, "log in user")
	}

	return &mgen.LoginPayload{User: u, SessionToken: s}, nil
}
